const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const C=require(path.join(root,'assets/core.js'));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const data=JSON.parse(html.split('window.PURSUITS_DATA=')[1].split(';</script>')[0]);
const rows=C.decode(data);
const openingState=C.initialState();
assert.equal(openingState.scope,'all');
assert.equal(C.filter(rows,openingState).length,21000);
for(const band of data.bands) assert(C.filter(rows,openingState).some(r=>r.band===band));
openingState.bands.push('Strong');assert.deepEqual(C.initialState().bands,[]);
const appSource=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
assert(appSource.includes('let state=C.initialState()'));
assert(appSource.includes('function reset(){state=C.initialState()'));
const base={scope:'strategic',product:'',region:'',industry:'',type:'',search:'',bands:[],sort:'score'};
const view=C.filter(rows,base);
assert.equal(rows.length,21000);assert.equal(view.length,8375);
assert.equal(C.totals(view).accounts,new Set(view.map(r=>r.account_id)).size);
assert.equal(C.totals(rows).pipeline,data.audit.open_pipeline);
assert.equal(C.filter(rows,{...base,scope:'all'}).length,21000);
const specific=C.filter(rows,{...base,product:'Security',region:'APAC',type:'Whitespace'});
assert(specific.length>0);assert(specific.every(r=>r.product==='Security'&&r.region==='APAC'&&r.type==='Whitespace'));
const bands=C.filter(rows,{...base,scope:'all',bands:['Strong','Emerging']});
assert.equal(bands.length,data.audit.bands.Strong+data.audit.bands.Emerging);assert(bands.every(r=>r.band==='Strong'||r.band==='Emerging'));
assert.equal(C.filter(rows,{...base,bands:['Very Strong']}).length,83);
assert(html.includes('<section id="explorer" class="explorer" hidden>'));
assert(html.includes('Account Explorer'));
assert(html.includes("$('explorer').hidden=view!=='explorer'"));
assert(C.filter(rows,{...base,product:'Database',bands:['Strong']}).length>0);
assert(C.filter(rows,{...base,product:'Database',bands:['Very Strong']}).length>0);
for(const band of data.bands)assert(C.filter(rows,{...base,scope:'all',bands:[band]}).length>0);
assert(html.indexOf('Unique accounts <span>')<html.indexOf('Strategic pursuits <span>'));
assert(html.includes('Opportunity overview'));assert(!html.includes('Where the signals converge'));
assert.equal(C.filter(rows,{...base,search:'does not exist'}).length,0);
assert(C.filter(rows,{...base,search:'a01376'}).every(r=>r.account_id==='A01376'));
const order=C.filter(rows,{...base,sort:'pipeline'});assert(order.every((r,i)=>!i||order[i-1].pipeline>=r.pipeline));
const csv=C.csv(view.slice(0,50));assert.equal(csv.split('\r\n').length,51);
assert(csv.includes('"product"'));assert(csv.includes('"pipeline"'));
assert(C.csv([{account_name:'=FORMULA()'}]).includes('"\'=FORMULA()"'));
assert(C.csv([{account_name:'quoted "name"'}]).includes('"quoted ""name"""'));
assert.equal(C.totals([]).pipeline,0);assert.equal(C.csv([]).split('\r\n').length,1);
assert.equal(new Set(view.map(r=>r.key)).size,view.length);
assert.deepEqual(C.order(view,'score').map(r=>r.rank),view.map(r=>r.rank));
console.log('PASS: source decoding; 21,000 rows; scope, compound filters, multi-band OR, empty state, account ID search, ranking, pipeline totals, CSV limits and escaping.');
